; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32VMIX_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_ESP32VMIX
lib_deps = 
	nrf24/RF24@^1.6.1
	adafruit/Adafruit NeoPixel@^1.15.5

[env:nano_TX]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
build_flags = -D MODE_TX_NANO
lib_deps = 
	nrf24/RF24@^1.6.1
	adafruit/Adafruit NeoPixel@^1.15.5

[env:nano_RX]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags = -D MODE_RX_NANO
lib_deps = 
	nrf24/RF24 @ ^1.6.1
	adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32SWITCHER_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_SWITCHER32
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp8266_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_port = COM4
build_flags = -D MODE_RX_ESP8266
upload_speed = 115200
lib_deps = 
	nrf24/RF24 @ ^1.6.1
	adafruit/Adafruit NeoPixel@^1.15.5

[env:esp8266WS_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_port = COM4
build_flags = -D MODE_RX_ESP8266_WS
upload_speed = 115200
lib_deps = 
	nrf24/RF24 @ ^1.6.1
	adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32_RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_RX_ESP32
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32MESH_RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_RX_ESP32_MESH
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32MESH_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_ESP32_MESH
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32UDP_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_ESP32UDP
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32UDP_RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_RX_ESP32UDP
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5

[env:esp32UDPWS_RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_RX_ESP32UDP_WS
lib_deps = FastLED@^3.6.0

[env:esp8266UDPWS_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_RX_ESP8266UDP_WS
lib_deps = FastLED@^3.6.0