; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32VMIX_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_ESP32VMIX
lib_deps = 
        nrf24/RF24@^1.6.1
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[platformio]
extra_configs = secrets.ini

[env:nano_TX]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
build_flags = -D MODE_TX_NANO
lib_deps = 
        nrf24/RF24@^1.6.1
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:nano_RX]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags = -D MODE_RX_NANO
lib_deps = 
        nrf24/RF24 @ ^1.6.1
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32SWITCHER_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = -D MODE_TX_SWITCHER32
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_port = COM4
build_flags = -D MODE_RX_ESP8266
upload_speed = 115200
lib_deps = 
        nrf24/RF24 @ ^1.6.1
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266WS_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
monitor_port = COM4
build_flags = -D MODE_RX_ESP8266_WS
upload_speed = 115200
lib_deps = 
        nrf24/RF24 @ ^1.6.1
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32_RX]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.101
espota_port = 3232
build_flags = 
        -D WIFI_SSID=\"${wifi.ssid}\"
        -D WIFI_PASSWORD=\"${wifi.password}\"
        -D MODE_RX_ESP32
        -D CAM_ID=0
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDP_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_TX_ESP32UDP
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        FastLED@^3.10.3
        links2004/WebSockets@^2.7.3

[env:esp8266UDP_TX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags = 
        -D MODE_TX_ESP8266UDP
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        FastLED@^3.10.3
        links2004/WebSockets@^2.7.3

[env:esp32UDP_RX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM0]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=0
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=1
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=2
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32UDPWS_RX_CAM3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_flags = 
        -D MODE_RX_ESP32UDP_WS
        -D CAM_ID=3
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266UDPWS_RX_CAM0]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 9600
upload_port = COM4
build_flags = 
        -D MODE_RX_ESP8266UDP_WS
        -D CAM_ID=0
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266UDPWS_RX_CAM1]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 9600
upload_port = COM4
build_flags = 
        -D MODE_RX_ESP8266UDP_WS
        -D CAM_ID=1
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266UDPWS_RX_CAM2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 9600
upload_port = COM4
build_flags = 
        -D MODE_RX_ESP8266UDP_WS
        -D CAM_ID=2
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp8266UDPWS_RX_CAM3]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 9600
upload_port = COM4
build_flags = 
        -D MODE_RX_ESP8266UDP_WS
        -D CAM_ID=3
        '-D WIFI_SSID="${wifi.ssid}"'
        '-D WIFI_PASSWORD="${wifi.password}"'
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        links2004/WebSockets@^2.7.3

[env:esp32ARBITER_RX]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.104
espota_port = 3232
build_flags = -D MODE_RX_ARBITER_ESP32
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        tzapu/WiFiManager@^2.0.17
        arduino-libraries/Arduino_JSON@^0.2.0
        links2004/WebSockets@^2.7.3

[env:esp8266ARBITER_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 9600
upload_port = COM4
build_flags = -D MODE_RX_ARBITER_ESP8266
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        tzapu/WiFiManager@^2.0.17
        arduino-libraries/Arduino_JSON@^0.2.0
        links2004/WebSockets@^2.7.3

[env:esp8266TALLYHUB_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 115200
upload_port = COM4
build_flags =
        -D MODE_RX_TALLYHUB_ESP8266
        -D LED_PIN=4
        -D LED_COUNT=1
lib_deps =
        adafruit/Adafruit NeoPixel@^1.15.5
        bblanchon/ArduinoJson@^7.0.4
        https://github.com/tzapu/WiFiManager.git

[env:esp32TALLYHUB_RX]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.104
espota_port = 3232
build_flags = 
        -D MODE_RX_TALLYHUB_ESP32
        -D LED_PIN=5
        -D LED_COUNT=1
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        bblanchon/ArduinoJson@^7.0.4
        https://github.com/tzapu/WiFiManager.git
        links2004/WebSockets@^2.7.3

[env:espRX_WSWEB]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.102
espota_port = 3232
build_flags = 
        -D MODE_RX_WEBSOCKET_32
        -D LED_PIN=5
        -D LED_COUNT=1
lib_deps = 
        adafruit/Adafruit NeoPixel@^1.15.5
        https://github.com/tzapu/WiFiManager.git
        links2004/WebSockets@^2.7.3
        tzapu/WiFiManager @ ^2.0.17

[wifi]
ssid = Tally_Light
password = malammalam
