; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev_TX]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_flags = -D MODE_TX_ESP32

[env:esp8266_RX]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
build_flags = -D MODE_RX_ESP8266
upload_speed = 115200

[env:nano_TX]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
build_flags = -D MODE_TX_NANO
lib_deps = tmrh20/RF24 @ ^1.4.10